### ISSUE TITLE
Add -f option to infrabox run to specify infrabox.json file

### ISSUE THREAD

**Issue by Steffen911** [InfraBox/infrabox#101]
It would be helpful to have the option to start specific infrabox files without losing the scope of the current working directory.

### Example
`infrabox run -f test/infrabox.json integration` to run the job "integration".

**Comment by ib-steffen** [comment]
implmented in v0.5.2

`infrabox -f infrabox/generator/tests.json {run|list|...}`

It still searches for your root infrabox.json. So you should run the command from your project's root dir. Alternatively we could think about adding a "root: true" field to the root infrabox.json. This would allow us to have infrabox.json files on every level in the FS and we could als determine the real root infrabox.json.
