### ISSUE TITLE
error output dependencies

### ISSUE THREAD

**Issue by stege** [InfraBox/infrabox#14]

**Comment by Steffen911** [comment]
Please add an onError function for jobs and/or the whole project, that starts another job.
A use case would be a cleanup job.

**Comment by ib-steffen** [comment]
We could add this by not only specifying the parent job but also the allowed states i.e.:
```json
{
    "name": "job-name",
    "depends_on": [{ "name": "parent-job-name", "on": ["finished", "error"]}]
}
```

So the job would only be executed if the parent job woul finish in state _finished_ or _error_. In any other situations it would not be started. Allowed states are:

- finished
- error
- failure
- skipped
- \* (shortcut for all states)

Open questions is if the aborted state is also allowed?

**Comment by Steffen911** [comment]
I would exclude the cleanup. Maybe you want to save the state on external resources by aborting. And you can always start the cleanup job manually afterwards.

Would it still be possible to just pass the jobname in the depends_on array? I think for most use cases the finished state is the only one that should be handled and it is therefor more convenient if don't have to specify it explicitly.
