### ISSUE TITLE
Containers aren't cleaned up after failed build

### ISSUE THREAD

**Issue by Steffen911** [InfraBox/infrabox#21]
If a container returns a non-zero exit code, but does not crash it isn't stopped and deleted after execution. This may lead to the following error in a later run:

> docker: Error response from daemon: Conflict. The container name "/CONTAINER_NAME" is already in use by container "CONTAINER_HASH". You have to remove (or rename) that container to be able to reuse that name.

**Comment by ib-steffen** [comment]
should be fixed in 0.3.1
