### ISSUE TITLE
Submit job with --job

### ISSUE THREAD

**Issue by Steffen911** [InfraBox/infrabox#22]
It's more intuitive to submit the job with --job=VALUE instead of --job-name=VALUE

Another way would be `infrabox run JOBNAME`

**Comment by ib-steffen** [comment]
`infrabox run JOBNAME` is now supported in 0.3.1

**Comment by Steffen911** [comment]
It's not possible to do a `infrabox run` anymore to run all:
![image](https://user-images.githubusercontent.com/14163614/30200933-314a590c-9479-11e7-9d16-10fbccd7df67.png)
