### ISSUE TITLE
infrabox run not possible

### ISSUE THREAD

**Issue by Steffen911** [InfraBox/infrabox#24]
Since #22 it is not possible to run `infrabox run` anymore:
![image](https://user-images.githubusercontent.com/14163614/30200989-70ce8a9e-9479-11e7-912d-477c24ba672b.png)

**Comment by ib-steffen** [comment]
what about a --all option?

**Comment by Steffen911** [comment]
Is it possible to make the job_name optional? I would prefer to start all with `infrabox run` and start a single job with  `infrabox run job_name`

Otherwise --all would be the best option IMO.

**Comment by ib-steffen** [comment]
fixed in 0.3.2
