### ISSUE TITLE
build_context property missing in the web documentation

### ISSUE THREAD

**Issue by windhamking** [InfraBox/infrabox#264]
It's found in dynamic workflow example in: https://github.com/InfraBox/examples/tree/master/dynamic_workflows

Without this, the default dynamic workflow context will be "/infrabox/output" or something, which will cause error when building docker image.

It's good to update this property on the web documentation.

**Comment by ib-steffen** [comment]
https://github.com/InfraBox/infrabox/blob/master/docs/doc.md
