### ISSUE TITLE
infrabox.ninja: my project is gone?

### ISSUE THREAD

**Issue by vasu1124** [InfraBox/infrabox#302]
Hi, 

my project [![Build Status](https://infrabox.ninja/api/v1/projects/1fbcb712-2cd8-408f-b50c-a7221b59128e/state.svg)](https://infrabox.ninja/dashboard/#/project/introspect) seems to have been lost (without my fiddling around). 
I recreated the project, and found subtle differences. E.g. the UI does not allow anymore for secret variables with '-' in the name. 
Also, I am not able to trigger a manual build (gives me an Internal Server Error).

Thanks,
Vasu

**Comment by ib-steffen** [comment]
infrabox.ninja has been cleared and setup from scratch. I'll add your project again this evening.
