### ISSUE TITLE
CLI: option -f has no effect

### ISSUE THREAD

**Issue by anbrsap** [InfraBox/infrabox#313]
The Infrabox CLI provides the `-f` option to specify the `infrabox.json` file to be used instead of looking into the current directory.

Apparently this does not work:

```
~/src$ ls -al infrabox-cli/infrabox.json
-rw-rw-rw- 1 ab ab 716 Apr 20 16:02 infrabox-cli/infrabox.json
~/src$ infrabox -f infrabox-cli/infrabox.json list
[infrabox] infrabox.json not found in current or any parent directory
```

**Comment by ib-steffen** [comment]
Should be fixed with 0.6.4. Previously the project root was handled differently and you always had to be in a repository with a infrabox.json. similar to git, but this is now not required anymore.
