### ISSUE TITLE
UI: cannot create Github project with non-Github user

### ISSUE THREAD

**Issue by anbrsap** [InfraBox/infrabox#320]
Tested with 0.9.8

- Sign-up with local user (non-Github)
- Start _Add Project_
- In step 2 press button `Connect Github Account' -> 404 `github/auth/connect`
- press back button -> back in step 1 of `Add Pproject`
- cannot select `Github` project type anymore

**Comment by ib-steffen** [comment]
please try again with 0.9.9, I could not reproduce it on our current build. re-open if issues persists.
