### ISSUE TITLE
UI: cannot trigger Github project build via UI

### ISSUE THREAD

**Issue by anbrsap** [InfraBox/infrabox#322]
tested with 0.9.8

- create new Github project
- on page `dashboard/#/project/<project_name>` select action `Trigger a new Build`
- enter existing branch, e.g. `master`
- press `TRIGGER` -> internal server error

**Comment by ib-steffen** [comment]
Works on our current build, maybe it was only borken in 0.9.8. We will release a new version later this day.

**Comment by ib-steffen** [comment]
please try 0.9.9 and re-open if issues still persists. In this case please provide the log output of the API pod. thanks
