### ISSUE TITLE
UI: broken link to data output of failed job

### ISSUE THREAD

**Issue by anbrsap** [InfraBox/infrabox#323]
tested with 0.9.8

- open `dashboard/#/project/<project_name>/build/<build_num>/<restart_num>/job/<job_name>` for a failed job
- choose action `Data Output` -> 404

**Comment by ib-steffen** [comment]
Currently we don't upload the output if a job failed. We have two options to tackle the broken link. Either upload output also for failed jobs or hide the link in this case. What option would you prefer?
